version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      routine-go:
        update-types: [patch, minor]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      routine-actions:
        update-types: [patch, minor]
