version: 2

project_name: terraform-provider-hubspot

before:
  hooks:
    - go mod verify

builds:
  - id: provider
    main: .
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '6'
      - '7'

archives:
  - id: provider
    formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}'
    files:
      - terraform-registry-manifest.json

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

signs:
  - artifacts: checksum
    args:
      - '--batch'
      - '--local-user'
      - '{{ .Env.GPG_FINGERPRINT }}'
      - '--output'
      - '${signature}'
      - '--detach-sign'
      - '${artifact}'

changelog:
  disable: true
