// Copyright (c) 2026 jackemcpherson
// SPDX-License-Identifier: MPL-2.0

package hubspot

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"
)

// FormClient owns the typed Forms v3 lifecycle boundary. Form identity is
// always the ID generated by HubSpot; names are presentation only.
type FormClient struct{ transport *Transport }

type FormDefinition struct {
	ID        string `json:"id"`
	Archived  bool   `json:"archived"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	FormDefinitionWrite
}

type FormDefinitionWrite struct {
	FormType            string                  `json:"formType"`
	Name                string                  `json:"name"`
	FieldGroups         []FormFieldGroup        `json:"fieldGroups"`
	Configuration       FormConfiguration       `json:"configuration"`
	DisplayOptions      FormDisplayOptions      `json:"displayOptions"`
	LegalConsentOptions FormLegalConsentOptions `json:"legalConsentOptions"`
}

type FormFieldGroup struct {
	GroupType    string      `json:"groupType"`
	RichTextType string      `json:"richTextType"`
	Fields       []FormField `json:"fields"`
}

// FormDependentField is intentionally empty: the supported resource contract
// always sends an empty dependentFields array.
type FormDependentField struct{}

type FormField struct {
	ObjectTypeID    string               `json:"objectTypeId"`
	Hidden          bool                 `json:"hidden"`
	Name            string               `json:"name"`
	DependentFields []FormDependentField `json:"dependentFields"`
	Label           string               `json:"label"`
	FieldType       string               `json:"fieldType"`
	Required        bool                 `json:"required"`
	Validation      FormFieldValidation  `json:"validation"`
	Description     string               `json:"description"`
	Placeholder     string               `json:"placeholder"`
}

type FormFieldValidation struct {
	BlockedEmailDomains []string `json:"blockedEmailDomains"`
	UseDefaultBlockList bool     `json:"useDefaultBlockList"`
}

type FormConfiguration struct {
	CreateNewContactForNewEmail bool                 `json:"createNewContactForNewEmail"`
	Editable                    bool                 `json:"editable"`
	AllowLinkToResetKnownValues bool                 `json:"allowLinkToResetKnownValues"`
	PostSubmitAction            FormPostSubmitAction `json:"postSubmitAction"`
	Language                    string               `json:"language"`
	PrePopulateKnownValues      bool                 `json:"prePopulateKnownValues"`
	Cloneable                   bool                 `json:"cloneable"`
	NotifyContactOwner          bool                 `json:"notifyContactOwner"`
	RecaptchaEnabled            bool                 `json:"recaptchaEnabled"`
	Archivable                  bool                 `json:"archivable"`
	NotifyRecipients            []string             `json:"notifyRecipients"`
}

type FormPostSubmitAction struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type FormDisplayOptions struct {
	RenderRawHTML    bool      `json:"renderRawHtml"`
	Theme            string    `json:"theme"`
	SubmitButtonText string    `json:"submitButtonText"`
	Style            FormStyle `json:"style"`
}

type FormStyle struct {
	LabelTextSize         string `json:"labelTextSize"`
	LegalConsentTextColor string `json:"legalConsentTextColor"`
	FontFamily            string `json:"fontFamily"`
	LegalConsentTextSize  string `json:"legalConsentTextSize"`
	BackgroundWidth       string `json:"backgroundWidth"`
	HelpTextSize          string `json:"helpTextSize"`
	SubmitFontColor       string `json:"submitFontColor"`
	LabelTextColor        string `json:"labelTextColor"`
	SubmitAlignment       string `json:"submitAlignment"`
	SubmitSize            string `json:"submitSize"`
	HelpTextColor         string `json:"helpTextColor"`
	SubmitColor           string `json:"submitColor"`
}

type FormLegalConsentOptions struct {
	Type string `json:"type"`
}

func formsPath() string { return "/marketing/v3/forms" }

func (c *FormClient) Create(ctx context.Context, input FormDefinitionWrite) (FormDefinition, error) {
	body, err := json.Marshal(input)
	if err != nil {
		return FormDefinition{}, err
	}
	var out FormDefinition
	if err := c.transport.Do(ctx, Operation{Name: "form-create", Method: http.MethodPost, Path: formsPath(), Replay: ReplayNever}, bytes.NewReader(body), &out); err != nil {
		return FormDefinition{}, err
	}
	if out.ID == "" {
		return FormDefinition{}, errors.New("HubSpot form response omitted id")
	}
	return out, nil
}

func (c *FormClient) Get(ctx context.Context, id string) (FormDefinition, error) {
	return c.get(ctx, id, false)
}

func (c *FormClient) GetArchived(ctx context.Context, id string) (FormDefinition, error) {
	return c.get(ctx, id, true)
}

func (c *FormClient) get(ctx context.Context, id string, archived bool) (FormDefinition, error) {
	if id == "" {
		return FormDefinition{}, errors.New("form id must not be empty")
	}
	path := formsPath() + "/" + url.PathEscape(id)
	operation := "form-read"
	if archived {
		path += "?archived=true"
		operation = "form-read-archived"
	}
	var out FormDefinition
	if err := c.transport.Do(ctx, Operation{Name: operation, Method: http.MethodGet, Path: path, Replay: ReplaySafe}, nil, &out); err != nil {
		return FormDefinition{}, err
	}
	if out.ID == "" {
		return FormDefinition{}, errors.New("HubSpot form response omitted id")
	}
	return out, nil
}

func (c *FormClient) Archive(ctx context.Context, id string) error {
	if id == "" {
		return errors.New("form id must not be empty")
	}
	return c.transport.Do(ctx, Operation{Name: "form-archive", Method: http.MethodDelete, Path: formsPath() + "/" + url.PathEscape(id), Replay: ReplayNever}, nil, nil)
}
