// Copyright (c) 2026 jackemcpherson
// SPDX-License-Identifier: MPL-2.0

package hubspot

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"
	"strconv"
	"time"
)

// FormClient owns the typed Forms v3 lifecycle boundary. Form identity is
// always the ID generated by HubSpot; names are presentation only.
type FormClient struct{ transport *Transport }

type FormDefinition struct {
	ID        string `json:"id"`
	Archived  bool   `json:"archived"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	FormDefinitionWrite
}

type FormDefinitionWrite struct {
	FormType            string                  `json:"formType"`
	Name                string                  `json:"name"`
	FieldGroups         []FormFieldGroup        `json:"fieldGroups"`
	Configuration       FormConfiguration       `json:"configuration"`
	DisplayOptions      FormDisplayOptions      `json:"displayOptions"`
	LegalConsentOptions FormLegalConsentOptions `json:"legalConsentOptions"`
}

// formDefinitionCreate carries service-required creation metadata without
// promoting it into Terraform desired state or subsequent PATCH requests.
type formDefinitionCreate struct {
	FormDefinitionWrite
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Archived  bool   `json:"archived"`
}

// FormDefinitionPatch is intentionally limited to the four supported mutable
// presentation subtrees. Nil members are omitted from the request entirely.
type FormDefinitionPatch struct {
	Name           *string             `json:"name,omitempty"`
	FieldGroups    *[]FormFieldGroup   `json:"fieldGroups,omitempty"`
	Configuration  *FormConfiguration  `json:"configuration,omitempty"`
	DisplayOptions *FormDisplayOptions `json:"displayOptions,omitempty"`
}

type FormFieldGroup struct {
	GroupType    string      `json:"groupType"`
	RichTextType string      `json:"richTextType"`
	RichText     string      `json:"richText,omitempty"`
	Fields       []FormField `json:"fields"`
}

// FormDependentField is intentionally empty: the supported resource contract
// always sends an empty dependentFields array.
type FormDependentField struct{}

type FormField struct {
	ObjectTypeID    string               `json:"objectTypeId"`
	Hidden          bool                 `json:"hidden"`
	Name            string               `json:"name"`
	DependentFields []FormDependentField `json:"dependentFields"`
	Label           string               `json:"label"`
	FieldType       string               `json:"fieldType"`
	Required        bool                 `json:"required"`
	Validation      FormFieldValidation  `json:"validation"`
	DefaultValue    string               `json:"defaultValue,omitempty"`
	Description     string               `json:"description"`
	Placeholder     string               `json:"placeholder"`
}

type FormFieldValidation struct {
	BlockedEmailDomains []string `json:"blockedEmailDomains"`
	UseDefaultBlockList bool     `json:"useDefaultBlockList"`
}

type FormConfiguration struct {
	CreateNewContactForNewEmail bool                 `json:"createNewContactForNewEmail"`
	Editable                    bool                 `json:"editable"`
	AllowLinkToResetKnownValues bool                 `json:"allowLinkToResetKnownValues"`
	PostSubmitAction            FormPostSubmitAction `json:"postSubmitAction"`
	Language                    string               `json:"language"`
	LifecycleStages             []FormLifecycleStage `json:"lifecycleStages,omitempty"`
	PrePopulateKnownValues      bool                 `json:"prePopulateKnownValues"`
	Cloneable                   bool                 `json:"cloneable"`
	NotifyContactOwner          bool                 `json:"notifyContactOwner"`
	RecaptchaEnabled            bool                 `json:"recaptchaEnabled"`
	Archivable                  bool                 `json:"archivable"`
	NotifyRecipients            []string             `json:"notifyRecipients"`
}

type FormLifecycleStage struct {
	ObjectTypeID string `json:"objectTypeId"`
	Value        string `json:"value"`
}

type FormPostSubmitAction struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type FormDisplayOptions struct {
	RenderRawHTML    bool      `json:"renderRawHtml"`
	Theme            string    `json:"theme"`
	SubmitButtonText string    `json:"submitButtonText"`
	Style            FormStyle `json:"style"`
	CSSClass         string    `json:"cssClass,omitempty"`
}

type FormStyle struct {
	LabelTextSize         string `json:"labelTextSize"`
	LegalConsentTextColor string `json:"legalConsentTextColor"`
	FontFamily            string `json:"fontFamily"`
	LegalConsentTextSize  string `json:"legalConsentTextSize"`
	BackgroundWidth       string `json:"backgroundWidth"`
	HelpTextSize          string `json:"helpTextSize"`
	SubmitFontColor       string `json:"submitFontColor"`
	LabelTextColor        string `json:"labelTextColor"`
	SubmitAlignment       string `json:"submitAlignment"`
	SubmitSize            string `json:"submitSize"`
	HelpTextColor         string `json:"helpTextColor"`
	SubmitColor           string `json:"submitColor"`
}

type FormLegalConsentOptions struct {
	Type string `json:"type"`
}

type formDefinitionPage struct {
	Results []FormDefinition `json:"results"`
	Paging  struct {
		Next struct {
			After string `json:"after"`
		} `json:"next"`
	} `json:"paging"`
}

func formsPath() string { return "/marketing/v3/forms" }

func (c *FormClient) Create(ctx context.Context, input FormDefinitionWrite) (FormDefinition, error) {
	timestamp := c.transport.clock().UTC().Format(time.RFC3339)
	body, err := json.Marshal(formDefinitionCreate{
		FormDefinitionWrite: input,
		CreatedAt:           timestamp,
		UpdatedAt:           timestamp,
		Archived:            false,
	})
	if err != nil {
		return FormDefinition{}, err
	}
	var out FormDefinition
	err = c.transport.Do(ctx, Operation{Name: "form-create", Method: http.MethodPost, Path: formsPath(), Replay: ReplayNever}, bytes.NewReader(body), &out)
	normalizeFormDefinition(&out)
	if err != nil {
		// A success response can be truncated after its generated ID. Preserve
		// that identity so the resource can recover by exact-ID read-back.
		return out, err
	}
	if out.ID == "" {
		return FormDefinition{}, errors.New("HubSpot form response omitted id")
	}
	return out, nil
}

func (c *FormClient) Get(ctx context.Context, id string) (FormDefinition, error) {
	return c.get(ctx, id, false)
}

func (c *FormClient) GetArchived(ctx context.Context, id string) (FormDefinition, error) {
	return c.get(ctx, id, true)
}

// List returns every active or archived Form definition by following HubSpot's
// cursor. It is intentionally an internal maintenance surface, not a provider
// data source or an identity lookup mechanism.
func (c *FormClient) List(ctx context.Context, archived bool) ([]FormDefinition, error) {
	results := make([]FormDefinition, 0)
	after := ""
	seen := make(map[string]struct{})
	for {
		query := url.Values{"archived": []string{strconv.FormatBool(archived)}, "limit": []string{"100"}}
		if after != "" {
			query.Set("after", after)
		}
		var page formDefinitionPage
		if err := c.transport.Do(ctx, Operation{
			Name: "form-list", Method: http.MethodGet, Path: formsPath() + "?" + query.Encode(), Replay: ReplaySafe,
		}, nil, &page); err != nil {
			return nil, err
		}
		for index := range page.Results {
			form := &page.Results[index]
			normalizeFormDefinition(form)
			if form.ID == "" {
				return nil, errors.New("HubSpot form list response omitted id")
			}
			results = append(results, *form)
		}
		next := page.Paging.Next.After
		if next == "" {
			return results, nil
		}
		if _, exists := seen[next]; exists {
			return nil, errors.New("HubSpot form list cursor repeated")
		}
		seen[next] = struct{}{}
		after = next
	}
}

func (c *FormClient) Update(ctx context.Context, id string, input FormDefinitionPatch) (FormDefinition, error) {
	if id == "" {
		return FormDefinition{}, errors.New("form id must not be empty")
	}
	if input.Name == nil && input.FieldGroups == nil && input.Configuration == nil && input.DisplayOptions == nil {
		return FormDefinition{}, errors.New("form patch must contain at least one managed subtree")
	}
	body, err := json.Marshal(input)
	if err != nil {
		return FormDefinition{}, err
	}
	var out FormDefinition
	if err := c.transport.Do(ctx, Operation{Name: "form-update", Method: http.MethodPatch, Path: formsPath() + "/" + url.PathEscape(id), Replay: ReplayNever}, bytes.NewReader(body), &out); err != nil {
		return FormDefinition{}, err
	}
	normalizeFormDefinition(&out)
	if out.ID == "" {
		return FormDefinition{}, errors.New("HubSpot form response omitted id")
	}
	if out.ID != id {
		return FormDefinition{}, errors.New("HubSpot form response returned a different id")
	}
	return out, nil
}

func (c *FormClient) get(ctx context.Context, id string, archived bool) (FormDefinition, error) {
	if id == "" {
		return FormDefinition{}, errors.New("form id must not be empty")
	}
	path := formsPath() + "/" + url.PathEscape(id)
	operation := "form-read"
	if archived {
		path += "?archived=true"
		operation = "form-read-archived"
	}
	var out FormDefinition
	if err := c.transport.Do(ctx, Operation{Name: operation, Method: http.MethodGet, Path: path, Replay: ReplaySafe}, nil, &out); err != nil {
		return FormDefinition{}, err
	}
	normalizeFormDefinition(&out)
	if out.ID == "" {
		return FormDefinition{}, errors.New("HubSpot form response omitted id")
	}
	return out, nil
}

func normalizeFormDefinition(form *FormDefinition) {
	for groupIndex := range form.FieldGroups {
		for fieldIndex := range form.FieldGroups[groupIndex].Fields {
			domains := form.FieldGroups[groupIndex].Fields[fieldIndex].Validation.BlockedEmailDomains
			if len(domains) == 1 && domains[0] == "" {
				form.FieldGroups[groupIndex].Fields[fieldIndex].Validation.BlockedEmailDomains = []string{}
			}
		}
	}
}

func (c *FormClient) Archive(ctx context.Context, id string) error {
	if id == "" {
		return errors.New("form id must not be empty")
	}
	return c.transport.Do(ctx, Operation{Name: "form-archive", Method: http.MethodDelete, Path: formsPath() + "/" + url.PathEscape(id), Replay: ReplayNever}, nil, nil)
}
